# Site settings
title: 苹果核 
contact: gaosboy
email : gaosboy@gmail.com

description: > # this means to ignore newlines until "baseurl:"
   除了苹果我们也卖别的
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pingguohe.net" # the base hostname & protocol for your site
twitter_username: 
github_username:  pingguohe

sass:
  sass_dir: _sass
  style: compressed

# Build settings
#highlighter: pygments
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
